source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-include-cache"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "logger", "~> 1.5"
gem "jekyll-data"
gem "jekyll-sitemap"
gem "jekyll-gist"
